### ISSUE TITLE
Infinite Loops and Broken Mechanics!

### ISSUE THREAD

**Issue by Astralika** [adambennett/StS-DuelistMod#3]
I super-unfortunately don't have any actual logs, since both soft-locked my game unless I save-and-quit, but two interactions I found that I'm 100% positive are bugs:

(Upgraded) Pumpking Resummons an upgraded Soul Bone Tower, which resummons 2 cards from the discard pile... But if Soul Bone Tower+ is one of only two monsters in the discard, it will resummon itself, and then resummon itself, and then resummon itself. It's nice that Soul Bone Tower isn't Exempt, since its main mechanic (if zombies were tributed) doesn't work on resummon, but it should probably not be able to resummon other Soul Bone Towers.

Also, Ultimate Offering's HP Loss doesn't work correctly with Temporary HP mechanics, and the game soft-locks if Ultimate Offering's HP loss puts you into what *should* kill you. That one's a bit more esoteric and was only really noticeable with the Hubris mod's Bottled Heart (which sets your max HP to 1 but grants you Temporary HP at the start of Every Fight), but I figured it still might be meaningful to bring up.

**Comment by adambennett** [comment]
Great finds! I will investigate these issues asap

**Comment by adambennett** [comment]
Fixed with v2.366.5 release
