### ISSUE TITLE
Playing "Plaguespreader Zombie" create infinite loops when there's no monster in the discard pile

### ISSUE THREAD

**Issue by ttphi88** [adambennett/StS-DuelistMod#5]
Thank you for creating this mod, I enjoy playing it.

The issue is similar to https://github.com/adambennett/StS-DuelistMod/issues/3, but I created new issue for easier tracking.

**Comment by adambennett** [comment]
This will be addressed in the next build as Plaguespreader will be nerfed considerably!

**Comment by adambennett** [comment]
Fixed with release of v2.483.0!
